export { default as HomePage } from './home/HomePage';
export { default as NotFound } from './404/NotFound';
export { default as Dashboard } from './admin/dashboard/Dashboard';
export { default as ProjectAdminPage } from './admin/projects/ProjectAdminPage';
export { default as ProjectAddPage } from './admin/projects/ProjectAddPage';
export { default as ProjectEditPage } from './admin/projects/ProjectEditPage';
export { default as Project } from './project/Project';
export { default as SignUpPage } from './admin/SignUp/SignUpPage';
export { default as SignInPage } from './admin/SignIn/SignInPage';
